### PR TITLE
Upgrade to node 12.4, and use smtp-server

### PR DESCRIPTION
**Pull request by DavidTanner**
Updated the library to use smtp-server, bluebird promises, and node 12.4.
The travis tests no longer run the code beautifier, just the mochaTest command.
Made more of the options needed for the smtp server as command line options.

### CODE REVIEW

**Comment by Flolagale** [comment]
Awesome! Your last commit says that all the tests pass, however the Travis build failed, any idea?
Let me review this one thoroughly.

**Comment by DavidTanner** [comment]
There are a few things I am not sure how the defaults should be handled.  smtp-connection defaults to requiring AUTH, I added a parameter to be able to turn it off but I am not sure if it should be off by default.

As for the tests, I just can't get them to fail like the server is.  I am running on OSX with node 0.12.4, and npm 2.10.1  Any ideas?

**Comment by dapriett** [comment]
+1

**Comment by Flolagale** [comment]
Ok, I'll dig into why the tests fail and I'll should be able to merge it begining of next week.

**Comment by Flolagale** [comment]
@DavidTanner @dapriett Guys, quick update. Sorry for the delay, I had a baby last week, needless to say did not had much time ;). I should be able to look at this very soon. 
@DavidTanner Would you mind updating the pull request with your latest commits? By the way I think that the tests are failing because .travis.yml is running the tests against node 0.10.

**Comment by DavidTanner** [comment]
I just updated the engine version in the package.json, but the travis config is set to use 0.12.4

**Comment by DavidTanner** [comment]
Now using node v0.12.4
$ node --version
v0.12.4
$ npm --version
2.10.1
$ nvm --version
0.23.3

**Comment by DavidTanner** [comment]
it won't work with node 10

**Comment by Flolagale** [comment]
@DavidTanner @dapriett Merged and published on npm. Mailin v3.0.0 needs node ~0.12.0, mailin ^2.0.0 is still compatible with older node versions.
@DavidTanner Thanks again !

**Pull request merged**
