### PR TITLE
merge forked repo into hardening for future dev

### PR DESCRIPTION
**Pull request by hellsan631**
Should solve issues #48, #51, & #54

Future development includes more tests, updating docs, more promises, and overall bug stompage

### CODE REVIEW

**Comment by hellsan631** [comment]
Some notes on a couple of the dev environment quality-of-life changes that I made in the beginning of developing this:

I removed the beautifier and linter. The beautifier was a little trouble-some because It moved a lot of things around that I didn't want touched (I lined up the var declarations for example), which produced cleaner code. The linter was also removed because I have a very nice linter built into atom (my IDE), and it was giving me errors about spacing, which meant I had to spend time debugging a linter when I could be coding. 

I also changed tab spacing to 2, and usually hoist my functions (put function declarations at the bottom of cope). 

I don't know if you are fine with these changes, or if you want to return to the old ways. I guess the choice is really up to you, but I always try to stay up to date with the general community JS style guides, and I find that these few improvements have made my code more readable.

**Comment by Flolagale** [comment]
@hellsan631 I'm totally ok removing the beautifier because it doesn't affect the lib stability. For the linter, I must admit that I like running it during the CI runs because it avoids some bugs coming from typos for instance. I am ok with changing some of its parameters though, for instance not checking the tab spacing!

There are some changes that were made to the `README.md`and `cli.js` files that we have to merge back.

I was thinking, I like the concept of the `MailinReport` class. To even further improve the encapsulation provided by this object, how about adding a `MailinReport#buildReport`method to into which we would move the promise chain currently located in `Mailin#onDataReady` [lines 393-414](https://github.com/hellsan631/mailin/blob/master/lib/mailin.js#L393). This would allow modifying this chain or even adding new reports without changing files not related to the `MailinReport`object. What do you think?

[How are internal errors handled?](https://github.com/hellsan631/mailin/blob/master/lib/mailin.js#L332):
Internal errors should bubble up to smtp-server and break the message reception, just as you coded it. No better way for the moment.

**Comment by hellsan631** [comment]
@Flolagale sure, that works. I don't normally use it, so if you can find a way to do without it, that would be best. I edited the readme just so i could easily access travis, and i also edited the CLI so it would stop throwing 'line is to long errors'. Feel free to merge those back.

I like the build report method idea.

For testing, how do you suppose we go about collecting valid samples that don't expose important information? Perhaps using a service like 10-20 minuet mail with throw away addresses, and collecting the email file and connection info. I would like to take out whats currently there, and merge all of these commits into one base commit using a rebase. Should I do that now, and refile this pull request?

**Comment by Flolagale** [comment]
Sure feel free to rebase now if you want

**Comment by hellsan631** [comment]
ok. Also edited the above post. :)

**Pull request closed without merging**
